class IRigidBody : public UCOM::IUnknown {
public:
	static inline uint32_t IHandle = 0x401A80;

	virtual ISimable *GetOwner();
	virtual bool IsSimple();
	virtual int GetIndex();
	virtual SimableType GetSimableType();
	virtual float GetRadius();
	virtual float GetMass();
	virtual float GetOOMass();
	virtual const UMath::Vector3 *GetPosition();
	virtual const UMath::Vector3 *GetLinearVelocity();
	virtual const UMath::Vector3 *GetAngularVelocity();
	virtual float GetSpeed();
	virtual float GetSpeedXZ();
	virtual const UMath::Vector3 *GetForwardVector();
	virtual const UMath::Vector3 *GetRightVector();
	virtual const UMath::Vector3 *GetUpVector();
	virtual const UMath::Matrix4 *GetTransform();
	virtual void GetOrientation(UMath::Vector4 *);
	virtual UMath::Vector3* GetDimension();
	virtual void GetDimension(UMath::Vector3*);
	virtual unsigned int GetTriggerFlags();
	virtual void GetPointVelocity(const UMath::Vector3 *, UMath::Vector3 *);
	virtual void SetPosition(const UMath::Vector3 *);
	virtual void SetLinearVelocity(const UMath::Vector3 *);
	virtual void SetAngularVelocity(const UMath::Vector3 *);
	virtual void SetRadius(float);
	virtual void SetMass(float);
	virtual void SetOrientation(const UMath::Matrix4 *);
	virtual void SetOrientation(const UMath::Vector4 *);
	virtual void ModifyXPos(float);
	virtual void ModifyYPos(float);
	virtual void ModifyZPos(float);
	virtual void Resolve(const UMath::Vector3 *, const UMath::Vector3 *);
	virtual void ResolveForce(const UMath::Vector3 *, const UMath::Vector3 *);
	virtual void _ResolveForce(const UMath::Vector3 *);
	virtual void ResolveTorque(const UMath::Vector3 *, const UMath::Vector3 *);
	virtual void _ResolveTorque(const UMath::Vector3 *);
	virtual const UMath::Vector3 *GetForce();
	virtual const UMath::Vector3 *GetTorque();
	virtual void Accelerate(const UMath::Vector3 *, float);
	virtual void OverrideIntertiaTensor(const UMath::Vector3 *);
	virtual void OverrideMass(float);
	virtual void OverrideFriction(float);
	virtual void OverrideCOG(const UMath::Vector3 *);
	virtual void ConvertLocalToWorld(UMath::Vector3 *, bool);
	virtual void ConvertWorldToLocal(UMath::Vector3 *, bool);
	virtual void SetCenterOfGravity(const UMath::Vector3 *);
	virtual const UMath::Vector3 *GetCenterOfGravity();
	virtual void SetInertiaTensor(const UMath::Vector3 *);
	virtual void GetInertiaTensor(UMath::Vector3 *);
	virtual bool IsIntegrating();
	virtual void DisableIntegration();
	virtual void EnableIntegration();
	virtual void Debug();
};